index.js

The duplicate statuses (`DOC/commit` and `DCO/pr`) are really annoying. The original idea was to run the check whether commits were pushed to master, or to a branch and added in a pull request. When a commit is pushed to master, you want to run any checks against just that single commit. But when it is part of a pull request, you want to check the status for all the commits, because the status of a PR is determined by the last commit.
Since there's nothing that can be done about commits to master, I think this plugin will have to rely on protected branches and force everything to come in via a PR.

Only check pull requests

---

lib/dco.js
test/dco.js

Fixes https://github.com/probot/dco/issues/29
Basically before I was trying to provide a solution that could potentially provide explanations for multiple commit errors, now I simply add the the most recent error to the description and pass that error t the description. I also take the first 140 characters of the description to make sure we don't go over the API limit.
I also tested this with a test and woo yay testing

truncate long descriptions to first 140 characters and add test

---

README.md

https://developercertificate.org/ uses `a, b, c, and d` instead of `1, 2, 3, and 4` which helps clarify:
```
> c. The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.
```

Modify How it works for clarity

---

.travis.yml

Followup from #45, this is no longer necessary.

chore: Remove greenkeeper-lockfile

---

README.md
index.js
lib/dco.js
test/dco.js

When `.github/dco.yml` specifies `require_signoff_for_members: false`,
members of the repository's owning organization can skip signing off
their commits, provided the commits are verified.
The rationale is that signoffs are useful when accepting contributions from outside the organization, but represent noise for commits by members of the organization.
Fixes #48.

Do not require sign-off for organization members

---

README.md
index.js

When the application is installed on a repository that is owned
by a regular user (as opposed to an organizaton) we now check if
the commit author is the same as the repository owner, and allow
skipping the sign-off only then.
This also fixed a bug that broke DCO on repositories owned by
users. The bug was introduced by #52.

Fix no-sign-off feature for user-owned repositories

---

lib/dco.js
test/dco.test.js

Fixes https://github.com/probot/dco/issues/21 by adding bot support! While I do think it would be better to look at `author.type` to check if it's Bot, that implementation fails all of our existing tests, unless we add an author object to them. I wasn't sure which would be better, but this implementation definitely works.
Thoughts @bkeepers?

add support for robot commits

---

lib/dco.js
test/dco.test.js

This PR doesn't actually alter any intended functionality. It
- rewrites the logic of `lib/dco.js` to be more readable and handle more cases in chunks
- changes the if statements to be 1 liners (except for the last one for readability) so now that file might actually be understandable at a quick glance
- adds `author` field to the tests so that we can check earlier in the code for `signoffRequired` and for bot users
- changes the bot user check to `author.type === 'Bot'` which is the most accurate way to check for a bot user (idk if a regular user could make their username have [bot] in it or if that's forbidden, but still)
The next step I wanna take is adding support for checking both the `commit.author.login` and `commit.committer.login` alongside the `commit.author.email` and …

rewrite logic to be more readable + add author to tests

---

lib/dco.js
test/dco.test.js

Finally closes #39 in checking the sign off against `commit.author` and `commit.committer` values
feedback welcome on the implementation, wasn't sure what a better way would be

checks for both commit.author and commit.committer

---

lib/dco.js
package.json
test/dco.test.js

Closes #69 final issues and [Sentry](https://sentry.io/probot/dco/) Unresolved type error issues.
So this is happening due to commits not being [linked to any user](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user), a state which is common for new GitHub accounts/users to be in.
In this state it appears the `author` field is null and we check in DCO for the `author.login` (aka your GitHub login), so I've made the check more thorough to avoid this issue.

add check for author && author.login to avoid errors when author is null

---

lib/dco.js
test/dco.test.js

Fixes https://github.com/probot/dco/issues/81
In #77 I introduced a regression that caused the DCO to always pass when the author was null which was not intended behavior. 
This PR fixes that issue and adds a test for this scenario.

Fix author being null bug

---

lib/dco.js
package.json
test/dco.test.js
test/index.test.js

Resolves #88
This PR updates to standard v12 (see [changelog](https://standardjs.com/changelog.html#1200---2018-08-28)) and fixes new violations by running `npx standard --fix`.

Update standard to v12

---

index.js

This prevents GitHub from reporting:
`DCO Successful in -1m`

Add started at

---

index.js

#100 introduced this, and per https://github.com/probot/dco/pull/100#pullrequestreview-189157631 I made it a fairly global thing.
Unfortunately, as shown in https://github.com/probot/dco/pull/100#issuecomment-455832013:
> Note: `712m` is imo _slightly_ better than `-1m`, but I can't imagine DCO taking that long to run...
The problem is explained in https://github.com/probot/dco/pull/100#issuecomment-455832161

Fix started at to be per request

---

index.js
test/fixtures/check_run.created-success.json
test/fixtures/check_run.created.json

The instructions given to users when they're signing off commits currently tell users to use `git push --force`, which is unsafe compared to `git push --force-with-lease`.
Here's a blog post that says it in much more detail than I ever could: https://developer.atlassian.com/blog/2015/04/force-with-lease/

fix: use "--force-with-lease" instead of "--force" in push hint

---

lib/dco.js
test/dco.test.js

Fixes https://github.com/probot/dco/issues/75
Commit https://github.com/hyperledger/iroha/pull/1832/commits/65631789e50ba4111c4be63bcd21450ad03b3fa3 contains the following message:
```
Add tests for GetRolePermissions query (#1710)
Signed-off-by: Igor Egorov <igor@soramitsu.co.jp>
Signed-off-by: Vadim Reutskiy <reutskiy@soramitsu.co.jp>
```
DCO reaction before this PR:
```
Expected "Vadim Rc sfai.88@gmail.com", but got "Igor Egorov igor@soramitsu.co.jp".
```
DCO reaction after this PR:
```
Can not find "Vadim Rc <sfai.88@gmail.com>", in ["Igor Egorov <igor@soramitsu.co.jp>", "Vadim Reutskiy <reutskiy@soramitsu.co.jp>"].
```
So, DCO is satisfied if it can find at least one valid SoB.

Allow multiple SoB lines

---

README.md

The integration configuration link appears to have changed and the
README was not updated while the repo description was.
Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>
-----
[View rendered README.md](https://github.com/tykeal/probot-dco/blob/fix_docs/README.md)

Fix broken configuration link in README

---

index.js

When a user is making changes via the GitHub web UI (for example, editing a
README.md in their browser using the edit button) they may not have a local
copy of the branch. This edits the failure message to include a link to
instructions on how to clone a PR locally.
Signed-off-by: Brian Warner <brian@bdwarner.com>

Add link to instructions to check out PR locally

---

docs/deploy.md

Reorganize page to look more like the current GitHub App page where Permissions and Events are separate sections.
Add missing `Checks` permissions.
-----
[View rendered docs/deploy.md](https://github.com/rspier/dco/blob/patch-1/docs/deploy.md)

Reorganize required permissions and events.

---

index.js
test/__snapshots__/index.test.js.snap

feat: use `--no-edit` flag to improve signing for a single commit

---

README.md
index.js
lib/dco.js
test/__snapshots__/index.test.js.snap
test/dco.test.js

This PR adds support for remediation commits and expands test coverage. In brief, a remediation commit is an additional way for projects to recognize valid, retroactive signoffs on commits which otherwise fail the Probot DCO checks. 
Remediations come in two flavors. Individual remediation commits allow an author to fix one or more failing commits by pushing an additional, properly signed-off commit with specific text indicating they apply their signoff retroactively. Third-party remediations allow someone other than the author to do this.
**About this PR**
First and foremost the default Probot DCO behavior is unchanged, although the default remediation text and recommendations are modified (for reasons explained in the commit message). Unless a project explicitly enables remediation …

Add support for remediation commits

---

.github/workflows/release.yml
.github/workflows/test.yml
README.md
api/github/webhooks/index.js
index.js
lib/dco.js
lib/requireMembers.js
package-lock.json
package.json
test/__snapshots__/index.test.js.snap
test/dco.test.js
test/fixtures/compare-success.json
test/index.test.js

null
-----
[View rendered README.md](https://github.com/probot/dco/blob/remediation-commits/README.md)

feat: remediation commits
